// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const browser: typeof import('wxt/browser').browser
  const createCategory: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/notes-db').createCategory
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createNote: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/notes-db').createNote
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const deleteCategory: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/notes-db').deleteCategory
  const deleteNote: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/notes-db').deleteNote
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAllCategories: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/notes-db').getAllCategories
  const getAllHighlights: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/db').getAllHighlights
  const getElementByXPath: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/xpath').getElementByXPath
  const getHighlightsForUrl: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/db').getHighlightsForUrl
  const getNote: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/notes-db').getNote
  const getNotesByCategory: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/notes-db').getNotesByCategory
  const getXPath: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/xpath').getXPath
  const injectModalStyles: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/modal').injectModalStyles
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const normalizeUrl: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/db').normalizeUrl
  const removeHighlight: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/db').removeHighlight
  const removeModal: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/modal').removeModal
  const renameCategory: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/notes-db').renameCategory
  const saveHighlight: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/db').saveHighlight
  const showHighlightModal: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/modal').showHighlightModal
  const storage: typeof import('wxt/utils/storage').storage
  const updateHighlight: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/db').updateHighlight
  const updateNote: typeof import('/Users/hzhou/GitHub/bridge-highlighter/utils/notes-db').updateNote
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { HighlightMetadata } from '/Users/hzhou/GitHub/bridge-highlighter/utils/modal'
  import('/Users/hzhou/GitHub/bridge-highlighter/utils/modal')
  // @ts-ignore
  export type { HighlightColor, HighlightPosition, PageHighlights, NoteCategory, Note } from '/Users/hzhou/GitHub/bridge-highlighter/utils/types'
  import('/Users/hzhou/GitHub/bridge-highlighter/utils/types')
}
